[[redirects]]
    from = "/streamplot"
    to = "/complex/"

[[redirects]]
    from = "/wave-transmission"
    to = "/wave-transmission-coefficient"

[[redirects]]
    from = "/translation-tool"
    to = "json-translation-tool"

[[redirects]]
    from = "/json-translation"
    to = "json-translation-tool"