[build.processing]
    skip_processing = false
[build.processing.css]
    bundle = true
    minify = false
[build.processing.js]
    bundle = true
    minify = false
[build.processing.html]
    pretty_urls = true
[build.processing.images]
    compress = true

[[redirects]]
    from = "/streamplot"
    to = "/complex/"

[[redirects]]
    from = "/wave-transmission"
    to = "/wave-transmission-coefficient"